# Generated by Django 5.2 on 2025-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(default='Sin descripción', max_length=30),
            preserve_default=False,
        ),
    ]
