# Generated by Django 5.2 on 2025-05-06 00:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descripcion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_producto'),
        ),
    ]
