# Generated by Django 5.2 on 2025-05-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permite_aderezos',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_promocion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_opciones', models.PositiveIntegerField(default=1)),
                ('productos_opcionales', models.ManyToManyField(blank=True, related_name='promos', to='core.producto')),
            ],
        ),
    ]
