# Generated by Django 5.2 on 2025-05-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_permite_aderezos_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='aderezos',
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes_extras',
            field=models.ManyToManyField(blank=True, to='core.ingredienteextra'),
        ),
    ]
