# Generated by Django 5.2 on 2025-05-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredienteextra_remove_producto_aderezos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteextra',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
