# Generated by Django 5.2 on 2025-05-11 03:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ingredienteextra_precio_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen_promocion',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_promocion'),
        ),
    ]
