# Generated by Django 5.2 on 2025-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promocion_imagen_promocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='cantidad_opciones',
        ),
        migrations.AddField(
            model_name='promocion',
            name='cantidad_productos_a_elegir',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de productos a elegir'),
        ),
    ]
